language: node_js
node_js:
- '10'
notifications:
  email: false
install:
- cd ..
- git clone https://github.com/dotabap/dotabap-validator.git
- git clone https://github.com/dotabap/dotabap-generated.git
- cd dotabap-validator
- npm install
- cd ..
script:
- dotabap-validator/validator dotabap-list/list.json $GITHUB_READ > dotabap-generated/generated.json
after_success:
- cd dotabap-generated
- git status
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git add -A
- git status
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GITHUB_WRITE@github.com/dotabap/dotabap-generated.git > /dev/null 2>&1
env:
  global:
  - secure: UrXInTEJ/nGIaAbm/ETyNyR+/SQMTOgkGq+OG62FMpA7mrh4/GtgzdgEHv3f3P88vx6GKTNA+l4Bc0gaixqtqwX7mrfyQ+QCIpRtyjJXRUEEynVHkYrTJtxYPo9kKvo/f75lKiLrvVNhvXqkHpq6rpYYzFighOj3BFj41Wujq5pq5lYqt3aqbMwnytIzeWcxYpPBbcVv4z3LV1sKj1Gxb9+0AwkNdZQcjBpnlrZAO4QESK+byfEOqKlDGsGc09dED0/Gska7NBzImO9FTbm+8wlTqO2u51JLWAr5Ut9JlnW/9ZAnuKJCtR15k/SNldrwJKEZ5ksGFe/RS3xdmWEIlr/hKKGGdqbyIy62wjVXz+SziLZToesEH0RdgzDiqCVX34s7nzkKmgzbRwGCs7d9si1AlYtl0x/R8Gn+6CRRQwqcLDj2j614+8pNO245RrWTez8N2Mf+eshraRLBZlhYOWXxUHlgH++Cf+it1KpLPimqLj5A2VmhJO4XzCeajWZXj0+MLuvCXtqHsPdbVq3tgtmKwFp3CeY7d9uRP+OOPOyLVxID61YwWzQ0kZtGby/CsXUOJDWdvpAf0NWs5Q3zrAwno0CW2G7Qonimt43+xku28G9fwk48UCYAWLOzBr9314LCQnORYYxfDVx0O0a5wCtuKzfINj8HohAaWM7rsBo=
  - secure: CbzdN/Bc/0BO7QAYT9SewJURF2ssO/Ad4SMHYbOwvkNsPoMZDuBlrMxo66O8WENlHNLsYnTZG6Hff/hhAgFRmHOgQrIB/z1xMtP53NQWPD8VvtxhwHiDPMeqvUX/qj10W7Qo26KW3jgjeMySfcbS8lx3OLG1peVGKb9akfefEAow2LoqUcKcvV0pEE6pAysunik/FNEJAR2FNHn5GnIvUke+Noy+P7rdUlucM0KLDsSdWU5gCYBKAqQ0na6pfRPdUR6spz8Uxj9oLcksuRgBZQFUuSIrO2rgBOTk/yXwDS8C8wzMIJ71fpArsDrdaOgAsUBXKmbsTruqQWKzp/K+gqX2SC1DO2O18fCZPomECw1D+l2LniO7sPgoJpHUCZ33+iFFC2Wl63p4fJ5abMKxtwasUV38Akto3wFTaMYmin92HOKIwS5QKBByiugQz5M0zrlPqT4CQjdnyy+h0OO4PEd6MvJwAp28Jm11ldcnaLdBG0tBMVTs/kBowtPEqGRezfkJSXxjk2eZdB3q5LjXePC4xssCiWveb6VbImUv82vxsz4kJeP4bYBI5BOfMsVuGR9CUg1EDBupStbN6b8Q36FAxe3V3uWRrtvhHYBuT+hmnTUDliax9SmNjei2LXd8Migdbvd9S134bvsUbSViyrJQKpkLCdEx0hI/22CKeks=
