language: node_js
node_js:
  - "8"
notifications:
  email: false
install:
  - cd ..
  - git clone https://github.com/dotabap/dotabap-validator.git
  - cd dotabap-validator
  - npm install
  - cd ..
script:
  - dotabap-validator/validator dotabap-list/list.json
